name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Make gradlew executable
        working-directory: ./complete
        run: chmod +x ./gradlew

      - name: Build Complete with Gradle
        working-directory: ./complete
        run: ./gradlew build

      - name: test
        run: ls

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sample.zip
          path: build/distributions/sample.zip
